apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advocateid-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: main
    path: src/helm-charts/app
    helm:
      valueFiles: [values.yaml, values-production.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
  revisionHistoryLimit: 5
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advocateid-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: staging
    path: src/helm-charts/app
    helm:
      valueFiles: [values.yaml, values-staging.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
  revisionHistoryLimit: 5
